artifacts_root: artifacts

data_transformation:
      train_data_path: data_correction/train_data.pkl
      val_data_path: data_correction/val_data.pkl

      # P
      root_dir: artifacts/data_transformation/${P}
      preprocessor_path: artifacts/data_transformation/${P}/preprocessor.pkl
      train_features_path: artifacts/data_transformation/${P}/train_features.pkl
      train_target_path: artifacts/data_transformation/${P}/train_target.pkl
      val_features_path: artifacts/data_transformation/${P}/val_features.pkl
      val_target_path: artifacts/data_transformation/${P}/val_target.pkl

model_trainer:
      train_feature_path: artifacts/data_transformation/${P}/train_features.pkl
      train_target_path: artifacts/data_transformation/${P}/train_target.pkl
      val_feature_path: artifacts/data_transformation/${P}/val_features.pkl
      val_target_path: artifacts/data_transformation/${P}/val_target.pkl

      root_dir: artifacts/model_trainer/${T}
      best_model_path: artifacts/model_trainer/${T}/best_model.pkl
      monitor_desc_folder_path: artifacts/monitor_desc
      list_monitor_components_path: artifacts/monitor_desc/list_monitor_components.pkl

model_evaluation:
      test_data_path: data_correction/test_data.pkl
      preprocessor_path: artifacts/data_transformation/${EP}/preprocessor.pkl
      model_path: artifacts/model_trainer/${E}/best_model.pkl

      root_dir: artifacts/model_evaluation
      result: artifacts/model_evaluation/result.txt
