artifacts_root: artifacts

data_transformation:
      train_data_path: artifacts/data_correction/train_data.pkl
      val_data_path: artifacts/data_correction/val_data.pkl

      # P
      root_dir: artifacts/${P}
      preprocessor_path: artifacts/${P}/preprocessor.pkl
      train_features_path: artifacts/${P}/train_features.pkl
      train_target_path: artifacts/${P}/train_target.pkl
      val_features_path: artifacts/${P}/val_features.pkl
      val_target_path: artifacts/${P}/val_target.pkl

# 4 in 1
model_trainer:
      # P
      train_feature_path: artifacts/${P}/train_features.pkl
      train_target_path: artifacts/${P}/train_target.pkl
      val_feature_path: artifacts/${P}/val_features.pkl
      val_target_path: artifacts/${P}/val_target.pkl

      # T Lưu các model và kết quả
      root_dir: artifacts/model_trainer/${T}
      best_model_path: artifacts/model_trainer/${T}/best_model.pkl
      monitor_desc_folder_path: artifacts/monitor_desc
      list_monitor_components_path: artifacts/monitor_desc/list_monitor_components.pkl

# MODEL_EVALUATION
model_evaluation:
      test_data_path: artifacts/data_correction/test_data.pkl

      # P
      preprocessor_path: artifacts/${EP}/preprocessor.pkl

      # MODEL_EVALUATION Model cần đánh giá
      model_path: artifacts/model_trainer/${E}/best_model.pkl
      root_dir: artifacts/model_evaluation
      result: artifacts/model_evaluation/result.txt
