stages:
      data_transformation:
            cmd: python src/regressor/pipeline/stage_03_data_transformation.py
            deps:
                  - artifacts/data_correction
            params:
                  - data_transformation

            outs:
                  - artifacts/data_transformation/${P}

      model_trainer:
            cmd: python src/regressor/pipeline/stage_04_model_training.py
            deps:
                  - artifacts/data_transformation/${P}
            params:
                  - model_name
            outs:
                  - artifacts/model_trainer/${T}
                  - artifacts/monitor_desc

      model_evaluation:
            cmd: python src/regressor/pipeline/stage_05_model_evaluation.py
            params:
                  - evaluated_data_transformation
                  - evaluated_model_name
            outs:
                  - artifacts/model_evaluation/${E}
